site_name: Documentation Quickstart

site_description: Just trying to setup a documentation CI
site_url: https://limpingpebble.github.io/demo-repository/

repo_url: https://github.com/LimpingPebble/demo-repository
edit_uri: edit/main/docs/docs

plugins:
  - search
  - mermaid2

theme:
  name: material
  palette:
    primary: green
    accent: light green
  font:
    text: Roboto
    code: Roboto Mono
